services:
  config-server:
    image: edaakkaya/turkcell45-config-server
    ports:
      - "8989:8989"
  discovery-server:
    image: edaakkaya/turkcell45-discovery-server
    ports:
      - "8761:8761"
  gateway-server:
    image: edaakkaya/tcell45-gateway-server
    ports:
      -  "8888:8888"
    depends_on:
      - config-server
    environment:
      - CONFIG_URI=http://config-server:8989